# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Python\HRM\update.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(788, 577)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_address = QtWidgets.QLabel(Dialog)
        self.label_address.setObjectName("label_address")
        self.gridLayout_2.addWidget(self.label_address, 4, 0, 1, 1)
        self.label_nation = QtWidgets.QLabel(Dialog)
        self.label_nation.setObjectName("label_nation")
        self.gridLayout_2.addWidget(self.label_nation, 5, 0, 1, 1)
        self.label_gender = QtWidgets.QLabel(Dialog)
        self.label_gender.setObjectName("label_gender")
        self.gridLayout_2.addWidget(self.label_gender, 2, 2, 1, 1)
        self.input_nation = QtWidgets.QComboBox(Dialog)
        self.input_nation.setObjectName("input_nation")
        self.gridLayout_2.addWidget(self.input_nation, 5, 1, 1, 1)
        self.input_qq = QtWidgets.QLineEdit(Dialog)
        self.input_qq.setObjectName("input_qq")
        self.gridLayout_2.addWidget(self.input_qq, 3, 3, 1, 1)
        self.input_birthplace = QtWidgets.QLineEdit(Dialog)
        self.input_birthplace.setObjectName("input_birthplace")
        self.gridLayout_2.addWidget(self.input_birthplace, 5, 3, 1, 1)
        self.label_birthday = QtWidgets.QLabel(Dialog)
        self.label_birthday.setObjectName("label_birthday")
        self.gridLayout_2.addWidget(self.label_birthday, 5, 4, 1, 1)
        self.input_birthday = QtWidgets.QDateEdit(Dialog)
        self.input_birthday.setObjectName("input_birthday")
        self.gridLayout_2.addWidget(self.input_birthday, 5, 5, 1, 1)
        self.label_department = QtWidgets.QLabel(Dialog)
        self.label_department.setObjectName("label_department")
        self.gridLayout_2.addWidget(self.label_department, 0, 0, 1, 1)
        self.input_position = QtWidgets.QComboBox(Dialog)
        self.input_position.setObjectName("input_position")
        self.gridLayout_2.addWidget(self.input_position, 1, 3, 1, 1)
        self.label_position = QtWidgets.QLabel(Dialog)
        self.label_position.setObjectName("label_position")
        self.gridLayout_2.addWidget(self.label_position, 1, 2, 1, 1)
        self.label_postcode = QtWidgets.QLabel(Dialog)
        self.label_postcode.setObjectName("label_postcode")
        self.gridLayout_2.addWidget(self.label_postcode, 4, 4, 1, 1)
        self.input_gender = QtWidgets.QComboBox(Dialog)
        self.input_gender.setObjectName("input_gender")
        self.gridLayout_2.addWidget(self.input_gender, 2, 3, 1, 1)
        self.label_qq = QtWidgets.QLabel(Dialog)
        self.label_qq.setObjectName("label_qq")
        self.gridLayout_2.addWidget(self.label_qq, 3, 2, 1, 1)
        self.label_phone = QtWidgets.QLabel(Dialog)
        self.label_phone.setObjectName("label_phone")
        self.gridLayout_2.addWidget(self.label_phone, 3, 0, 1, 1)
        self.label_birthplace = QtWidgets.QLabel(Dialog)
        self.label_birthplace.setObjectName("label_birthplace")
        self.gridLayout_2.addWidget(self.label_birthplace, 5, 2, 1, 1)
        self.label_company = QtWidgets.QLabel(Dialog)
        self.label_company.setObjectName("label_company")
        self.gridLayout_2.addWidget(self.label_company, 0, 2, 1, 1)
        self.input_company = QtWidgets.QComboBox(Dialog)
        self.input_company.setObjectName("input_company")
        self.gridLayout_2.addWidget(self.input_company, 0, 3, 1, 1)
        self.label_department_2 = QtWidgets.QLabel(Dialog)
        self.label_department_2.setObjectName("label_department_2")
        self.gridLayout_2.addWidget(self.label_department_2, 0, 4, 1, 1)
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setObjectName("label_name")
        self.gridLayout_2.addWidget(self.label_name, 2, 0, 1, 1)
        self.input_name = QtWidgets.QLineEdit(Dialog)
        self.input_name.setObjectName("input_name")
        self.gridLayout_2.addWidget(self.input_name, 2, 1, 1, 1)
        self.input_positioncat = QtWidgets.QComboBox(Dialog)
        self.input_positioncat.setObjectName("input_positioncat")
        self.gridLayout_2.addWidget(self.input_positioncat, 1, 1, 1, 1)
        self.label_positiontitle = QtWidgets.QLabel(Dialog)
        self.label_positiontitle.setObjectName("label_positiontitle")
        self.gridLayout_2.addWidget(self.label_positiontitle, 1, 4, 1, 1)
        self.label_email = QtWidgets.QLabel(Dialog)
        self.label_email.setObjectName("label_email")
        self.gridLayout_2.addWidget(self.label_email, 2, 4, 1, 1)
        self.label_positioncat = QtWidgets.QLabel(Dialog)
        self.label_positioncat.setObjectName("label_positioncat")
        self.gridLayout_2.addWidget(self.label_positioncat, 1, 0, 1, 1)
        self.input_phone = QtWidgets.QLineEdit(Dialog)
        self.input_phone.setObjectName("input_phone")
        self.gridLayout_2.addWidget(self.input_phone, 3, 1, 1, 1)
        self.label_mobilephone = QtWidgets.QLabel(Dialog)
        self.label_mobilephone.setObjectName("label_mobilephone")
        self.gridLayout_2.addWidget(self.label_mobilephone, 3, 4, 1, 1)
        self.input_group = QtWidgets.QComboBox(Dialog)
        self.input_group.setObjectName("input_group")
        self.gridLayout_2.addWidget(self.input_group, 0, 1, 1, 1)
        self.label_hobby = QtWidgets.QLabel(Dialog)
        self.label_hobby.setObjectName("label_hobby")
        self.gridLayout_2.addWidget(self.label_hobby, 9, 4, 1, 1)
        self.label_education = QtWidgets.QLabel(Dialog)
        self.label_education.setObjectName("label_education")
        self.gridLayout_2.addWidget(self.label_education, 7, 2, 1, 1)
        self.input_booker = QtWidgets.QLineEdit(Dialog)
        self.input_booker.setObjectName("input_booker")
        self.gridLayout_2.addWidget(self.input_booker, 8, 7, 1, 1)
        self.input_vitae = QtWidgets.QTextEdit(Dialog)
        self.input_vitae.setObjectName("input_vitae")
        self.gridLayout_2.addWidget(self.input_vitae, 10, 1, 1, 7)
        self.label_major = QtWidgets.QLabel(Dialog)
        self.label_major.setObjectName("label_major")
        self.gridLayout_2.addWidget(self.label_major, 7, 6, 1, 1)
        self.input_openingbank = QtWidgets.QLineEdit(Dialog)
        self.input_openingbank.setObjectName("input_openingbank")
        self.gridLayout_2.addWidget(self.input_openingbank, 8, 3, 1, 1)
        self.input_salary = QtWidgets.QComboBox(Dialog)
        self.input_salary.setObjectName("input_salary")
        self.gridLayout_2.addWidget(self.input_salary, 8, 1, 1, 1)
        self.label_faith = QtWidgets.QLabel(Dialog)
        self.label_faith.setObjectName("label_faith")
        self.gridLayout_2.addWidget(self.label_faith, 6, 0, 1, 1)
        self.label_ethnicity = QtWidgets.QLabel(Dialog)
        self.label_ethnicity.setObjectName("label_ethnicity")
        self.gridLayout_2.addWidget(self.label_ethnicity, 5, 6, 1, 1)
        self.input_educationtime = QtWidgets.QComboBox(Dialog)
        self.input_educationtime.setObjectName("input_educationtime")
        self.gridLayout_2.addWidget(self.input_educationtime, 7, 5, 1, 1)
        self.input_faith = QtWidgets.QComboBox(Dialog)
        self.input_faith.setObjectName("input_faith")
        self.gridLayout_2.addWidget(self.input_faith, 6, 1, 1, 1)
        self.input_relationship = QtWidgets.QTextEdit(Dialog)
        self.input_relationship.setObjectName("input_relationship")
        self.gridLayout_2.addWidget(self.input_relationship, 11, 1, 1, 7)
        self.label_remarks = QtWidgets.QLabel(Dialog)
        self.label_remarks.setObjectName("label_remarks")
        self.gridLayout_2.addWidget(self.label_remarks, 12, 0, 1, 1)
        self.input_identification = QtWidgets.QLineEdit(Dialog)
        self.input_identification.setObjectName("input_identification")
        self.gridLayout_2.addWidget(self.input_identification, 6, 5, 1, 1)
        self.label_booktime = QtWidgets.QLabel(Dialog)
        self.label_booktime.setObjectName("label_booktime")
        self.gridLayout_2.addWidget(self.label_booktime, 9, 0, 1, 1)
        self.label_identification = QtWidgets.QLabel(Dialog)
        self.label_identification.setObjectName("label_identification")
        self.gridLayout_2.addWidget(self.label_identification, 6, 4, 1, 1)
        self.input_remarks = QtWidgets.QTextEdit(Dialog)
        self.input_remarks.setObjectName("input_remarks")
        self.gridLayout_2.addWidget(self.input_remarks, 12, 1, 1, 7)
        self.input_education = QtWidgets.QComboBox(Dialog)
        self.input_education.setObjectName("input_education")
        self.gridLayout_2.addWidget(self.input_education, 7, 3, 1, 1)
        self.label_age_data = QtWidgets.QLabel(Dialog)
        self.label_age_data.setObjectName("label_age_data")
        self.gridLayout_2.addWidget(self.label_age_data, 7, 1, 1, 1)
        self.input_hobby = QtWidgets.QLineEdit(Dialog)
        self.input_hobby.setObjectName("input_hobby")
        self.gridLayout_2.addWidget(self.input_hobby, 9, 5, 1, 1)
        self.input_ethnicity = QtWidgets.QComboBox(Dialog)
        self.input_ethnicity.setObjectName("input_ethnicity")
        self.gridLayout_2.addWidget(self.input_ethnicity, 5, 7, 1, 1)
        self.label_educationtime = QtWidgets.QLabel(Dialog)
        self.label_educationtime.setObjectName("label_educationtime")
        self.gridLayout_2.addWidget(self.label_educationtime, 7, 4, 1, 1)
        self.label_openingbank = QtWidgets.QLabel(Dialog)
        self.label_openingbank.setObjectName("label_openingbank")
        self.gridLayout_2.addWidget(self.label_openingbank, 8, 2, 1, 1)
        self.input_politicalstatus = QtWidgets.QComboBox(Dialog)
        self.input_politicalstatus.setObjectName("input_politicalstatus")
        self.gridLayout_2.addWidget(self.input_politicalstatus, 6, 3, 1, 1)
        self.input_major = QtWidgets.QComboBox(Dialog)
        self.input_major.setObjectName("input_major")
        self.gridLayout_2.addWidget(self.input_major, 7, 7, 1, 1)
        self.label_booktime_data = QtWidgets.QLabel(Dialog)
        self.label_booktime_data.setObjectName("label_booktime_data")
        self.gridLayout_2.addWidget(self.label_booktime_data, 9, 1, 1, 1)
        self.label_account = QtWidgets.QLabel(Dialog)
        self.label_account.setObjectName("label_account")
        self.gridLayout_2.addWidget(self.label_account, 8, 4, 1, 1)
        self.input_speciality = QtWidgets.QLineEdit(Dialog)
        self.input_speciality.setObjectName("input_speciality")
        self.gridLayout_2.addWidget(self.input_speciality, 9, 3, 1, 1)
        self.label_age = QtWidgets.QLabel(Dialog)
        self.label_age.setObjectName("label_age")
        self.gridLayout_2.addWidget(self.label_age, 7, 0, 1, 1)
        self.input_account = QtWidgets.QLineEdit(Dialog)
        self.input_account.setObjectName("input_account")
        self.gridLayout_2.addWidget(self.input_account, 8, 5, 1, 1)
        self.label_politicalstatus = QtWidgets.QLabel(Dialog)
        self.label_politicalstatus.setObjectName("label_politicalstatus")
        self.gridLayout_2.addWidget(self.label_politicalstatus, 6, 2, 1, 1)
        self.label_socialsecurity = QtWidgets.QLabel(Dialog)
        self.label_socialsecurity.setObjectName("label_socialsecurity")
        self.gridLayout_2.addWidget(self.label_socialsecurity, 6, 6, 1, 1)
        self.label_salary = QtWidgets.QLabel(Dialog)
        self.label_salary.setObjectName("label_salary")
        self.gridLayout_2.addWidget(self.label_salary, 8, 0, 1, 1)
        self.label_booker = QtWidgets.QLabel(Dialog)
        self.label_booker.setObjectName("label_booker")
        self.gridLayout_2.addWidget(self.label_booker, 8, 6, 1, 1)
        self.label_speciality = QtWidgets.QLabel(Dialog)
        self.label_speciality.setObjectName("label_speciality")
        self.gridLayout_2.addWidget(self.label_speciality, 9, 2, 1, 1)
        self.label_vitae = QtWidgets.QLabel(Dialog)
        self.label_vitae.setObjectName("label_vitae")
        self.gridLayout_2.addWidget(self.label_vitae, 10, 0, 1, 1)
        self.label_relationship = QtWidgets.QLabel(Dialog)
        self.label_relationship.setObjectName("label_relationship")
        self.gridLayout_2.addWidget(self.label_relationship, 11, 0, 1, 1)
        self.input_socialsecurity = QtWidgets.QLineEdit(Dialog)
        self.input_socialsecurity.setObjectName("input_socialsecurity")
        self.gridLayout_2.addWidget(self.input_socialsecurity, 6, 7, 1, 1)
        self.input_email = QtWidgets.QLineEdit(Dialog)
        self.input_email.setObjectName("input_email")
        self.gridLayout_2.addWidget(self.input_email, 2, 5, 1, 2)
        self.input_avatar = QtWidgets.QGraphicsView(Dialog)
        self.input_avatar.setMaximumSize(QtCore.QSize(111, 124))
        self.input_avatar.setObjectName("input_avatar")
        self.gridLayout_2.addWidget(self.input_avatar, 0, 7, 5, 1)
        self.input_department = QtWidgets.QComboBox(Dialog)
        self.input_department.setObjectName("input_department")
        self.gridLayout_2.addWidget(self.input_department, 0, 5, 1, 2)
        self.input_positiontitle = QtWidgets.QComboBox(Dialog)
        self.input_positiontitle.setObjectName("input_positiontitle")
        self.gridLayout_2.addWidget(self.input_positiontitle, 1, 5, 1, 2)
        self.input_postcode = QtWidgets.QLineEdit(Dialog)
        self.input_postcode.setObjectName("input_postcode")
        self.gridLayout_2.addWidget(self.input_postcode, 4, 5, 1, 2)
        self.input_mobilephone = QtWidgets.QLineEdit(Dialog)
        self.input_mobilephone.setObjectName("input_mobilephone")
        self.gridLayout_2.addWidget(self.input_mobilephone, 3, 5, 1, 2)
        self.input_address = QtWidgets.QLineEdit(Dialog)
        self.input_address.setObjectName("input_address")
        self.gridLayout_2.addWidget(self.input_address, 4, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.button_submit = QtWidgets.QPushButton(Dialog)
        self.button_submit.setObjectName("button_submit")
        self.horizontalLayout_5.addWidget(self.button_submit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.button_clear = QtWidgets.QPushButton(Dialog)
        self.button_clear.setObjectName("button_clear")
        self.horizontalLayout_5.addWidget(self.button_clear)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.input_group, self.input_company)
        Dialog.setTabOrder(self.input_company, self.input_department)
        Dialog.setTabOrder(self.input_department, self.input_positioncat)
        Dialog.setTabOrder(self.input_positioncat, self.input_position)
        Dialog.setTabOrder(self.input_position, self.input_positiontitle)
        Dialog.setTabOrder(self.input_positiontitle, self.input_name)
        Dialog.setTabOrder(self.input_name, self.input_gender)
        Dialog.setTabOrder(self.input_gender, self.input_email)
        Dialog.setTabOrder(self.input_email, self.input_phone)
        Dialog.setTabOrder(self.input_phone, self.input_qq)
        Dialog.setTabOrder(self.input_qq, self.input_mobilephone)
        Dialog.setTabOrder(self.input_mobilephone, self.input_address)
        Dialog.setTabOrder(self.input_address, self.input_postcode)
        Dialog.setTabOrder(self.input_postcode, self.input_nation)
        Dialog.setTabOrder(self.input_nation, self.input_birthplace)
        Dialog.setTabOrder(self.input_birthplace, self.input_ethnicity)
        Dialog.setTabOrder(self.input_ethnicity, self.input_faith)
        Dialog.setTabOrder(self.input_faith, self.input_politicalstatus)
        Dialog.setTabOrder(self.input_politicalstatus, self.input_identification)
        Dialog.setTabOrder(self.input_identification, self.input_socialsecurity)
        Dialog.setTabOrder(self.input_socialsecurity, self.input_education)
        Dialog.setTabOrder(self.input_education, self.input_educationtime)
        Dialog.setTabOrder(self.input_educationtime, self.input_major)
        Dialog.setTabOrder(self.input_major, self.input_salary)
        Dialog.setTabOrder(self.input_salary, self.input_openingbank)
        Dialog.setTabOrder(self.input_openingbank, self.input_account)
        Dialog.setTabOrder(self.input_account, self.input_booker)
        Dialog.setTabOrder(self.input_booker, self.input_speciality)
        Dialog.setTabOrder(self.input_speciality, self.input_hobby)
        Dialog.setTabOrder(self.input_hobby, self.input_vitae)
        Dialog.setTabOrder(self.input_vitae, self.input_relationship)
        Dialog.setTabOrder(self.input_relationship, self.input_remarks)
        Dialog.setTabOrder(self.input_remarks, self.input_avatar)
        Dialog.setTabOrder(self.input_avatar, self.button_submit)
        Dialog.setTabOrder(self.button_submit, self.button_clear)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_status.setText(_translate("Dialog", "你正在做的业务是：人力资源--人力资源档案管理--人力资源档案登记"))
        self.label_address.setText(_translate("Dialog", "住址"))
        self.label_nation.setText(_translate("Dialog", "国籍"))
        self.label_gender.setText(_translate("Dialog", "性别"))
        self.label_birthday.setText(_translate("Dialog", "生日"))
        self.label_department.setText(_translate("Dialog", "I级机构"))
        self.label_position.setText(_translate("Dialog", "职位名称"))
        self.label_postcode.setText(_translate("Dialog", "邮编"))
        self.label_qq.setText(_translate("Dialog", "qq"))
        self.label_phone.setText(_translate("Dialog", "电话"))
        self.label_birthplace.setText(_translate("Dialog", "出生地"))
        self.label_company.setText(_translate("Dialog", "II级机构"))
        self.label_department_2.setText(_translate("Dialog", "III级机构"))
        self.label_name.setText(_translate("Dialog", "姓名"))
        self.label_positiontitle.setText(_translate("Dialog", "职称"))
        self.label_email.setText(_translate("Dialog", "电子邮箱"))
        self.label_positioncat.setText(_translate("Dialog", "职位分类"))
        self.label_mobilephone.setText(_translate("Dialog", "手机"))
        self.label_hobby.setText(_translate("Dialog", "爱好"))
        self.label_education.setText(_translate("Dialog", "学历"))
        self.label_major.setText(_translate("Dialog", "学历专业"))
        self.label_faith.setText(_translate("Dialog", "宗教信仰"))
        self.label_ethnicity.setText(_translate("Dialog", "民族"))
        self.label_remarks.setText(_translate("Dialog", "备注"))
        self.label_booktime.setText(_translate("Dialog", "建档时间"))
        self.label_identification.setText(_translate("Dialog", "身份证号码"))
        self.label_age_data.setText(_translate("Dialog", "TextLabel"))
        self.label_educationtime.setText(_translate("Dialog", "教育年限"))
        self.label_openingbank.setText(_translate("Dialog", "开户行"))
        self.label_booktime_data.setText(_translate("Dialog", "datetime"))
        self.label_account.setText(_translate("Dialog", "账号"))
        self.label_age.setText(_translate("Dialog", "年龄"))
        self.label_politicalstatus.setText(_translate("Dialog", "政治面貌"))
        self.label_socialsecurity.setText(_translate("Dialog", "社会保障号码"))
        self.label_salary.setText(_translate("Dialog", "薪酬标准"))
        self.label_booker.setText(_translate("Dialog", "登记人"))
        self.label_speciality.setText(_translate("Dialog", "特长"))
        self.label_vitae.setText(_translate("Dialog", "个人履历"))
        self.label_relationship.setText(_translate("Dialog", "家庭关系信息"))
        self.button_submit.setText(_translate("Dialog", "提交"))
        self.button_clear.setText(_translate("Dialog", "清除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

