# -*- coding: utf-8 -*-

from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QDialog

from .Ui.Ui_clerkdetail import Ui_Dialog

class clerk_query_event(QDialog, Ui_Dialog):
    
    clerk = None
    
    def __init__(self, clerk, parent=None):
        self.clerk = clerk
        super(clerk_query_event, self).__init__(parent)
        self.setupUi(self)
        self.label_status.setText('你正在做的业务是：人力资源->人力资源档案管理->人力资源档案登记查询')
        self.button_submit.setText('关闭')
        self.button_clear.close()
        self.input_group.addItem(clerk.group.name)
        self.input_company.addItem(clerk.company.name)
        self.input_department.addItem(clerk.department.name)
        self.input_positioncat.addItem(clerk.position.category.name)
        self.input_position.addItem(clerk.position.name)
        self.input_positiontitle.addItem(clerk.positiontitle.name)
        self.input_salary.addItem(clerk.salary.name)
        self.input_name.setText(clerk.name)
        self.input_gender.setCurrentText(clerk.gender)
        self.input_email.setText(clerk.email)
        self.input_phone.setText(clerk.phone)
        self.input_qq.setText(clerk.qq)
        self.input_mobilephone.setText(clerk.mobilephone)
        self.input_address.setText(clerk.address)
        self.input_postcode.setText(clerk.postcode)
        self.input_nation.setCurrentText(clerk.nation)
        self.input_birthplace.setText(clerk.birthplace)
        self.input_birthday.setDate(clerk.birthday)
        self.input_ethnicity.setCurrentText(clerk.ethnicity)
        self.input_faith.setCurrentText(clerk.faith)
        self.input_politicalstatus.setCurrentText(clerk.politicalstatus)
        self.input_identification.setText(clerk.identification)
        self.input_socialsecurity.setText(clerk.socialsecurity)
        self.input_education.setCurrentText(clerk.education)
        self.input_educationtime.setCurrentText(clerk.educationtime)
        self.input_major.setText(clerk.major)
        self.input_openingbank.setText(clerk.openingbank)
        self.input_account.setText(clerk.account)
        self.input_speciality.setText(clerk.speciality)
        self.input_hobby.setText(clerk.hobby)
        self.input_vitae.setText(clerk.vitae)
        self.input_relationship.setText(clerk.relationship)
        self.input_remarks.setText(clerk.remarks)
        self.input_name.setReadOnly(True)
        self.input_email.setReadOnly(True)
        self.input_phone.setReadOnly(True)
        self.input_qq.setReadOnly(True)
        self.input_mobilephone.setReadOnly(True)
        self.input_address.setReadOnly(True)
        self.input_postcode.setReadOnly(True)
        self.input_birthplace.setReadOnly(True)
        self.input_birthday.setReadOnly(True)
        self.input_identification.setReadOnly(True)
        self.input_socialsecurity.setReadOnly(True)
        self.input_major.setReadOnly(True)
        self.input_openingbank.setReadOnly(True)
        self.input_account.setReadOnly(True)
        self.input_speciality.setReadOnly(True)
        self.input_hobby.setReadOnly(True)
        self.input_vitae.setReadOnly(True)
        self.input_relationship.setReadOnly(True)
        self.input_remarks.setReadOnly(True)
        self.input_gender.setEditable(False)
        self.input_nation.setEditable(False)
        self.input_ethnicity.setEditable(False)
        self.input_faith.setEditable(False)
        self.input_politicalstatus.setEditable(False)
        self.input_education.setEditable(False)
        self.input_educationtime.setEditable(False)
    
    @pyqtSlot()
    def on_button_submit_clicked(self):
        self.close()
