# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Python\HRM\main\Ui\create.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(788, 579)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_address = QtWidgets.QLabel(Dialog)
        self.label_address.setObjectName("label_address")
        self.gridLayout_2.addWidget(self.label_address, 4, 0, 1, 1)
        self.label_nation = QtWidgets.QLabel(Dialog)
        self.label_nation.setObjectName("label_nation")
        self.gridLayout_2.addWidget(self.label_nation, 5, 0, 1, 1)
        self.label_gender = QtWidgets.QLabel(Dialog)
        self.label_gender.setObjectName("label_gender")
        self.gridLayout_2.addWidget(self.label_gender, 2, 2, 1, 1)
        self.input_nation = QtWidgets.QComboBox(Dialog)
        self.input_nation.setObjectName("input_nation")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.input_nation.addItem("")
        self.gridLayout_2.addWidget(self.input_nation, 5, 1, 1, 1)
        self.input_qq = QtWidgets.QLineEdit(Dialog)
        self.input_qq.setObjectName("input_qq")
        self.gridLayout_2.addWidget(self.input_qq, 3, 3, 1, 1)
        self.input_birthplace = QtWidgets.QLineEdit(Dialog)
        self.input_birthplace.setObjectName("input_birthplace")
        self.gridLayout_2.addWidget(self.input_birthplace, 5, 3, 1, 1)
        self.label_birthday = QtWidgets.QLabel(Dialog)
        self.label_birthday.setObjectName("label_birthday")
        self.gridLayout_2.addWidget(self.label_birthday, 5, 4, 1, 1)
        self.input_birthday = QtWidgets.QDateEdit(Dialog)
        self.input_birthday.setObjectName("input_birthday")
        self.gridLayout_2.addWidget(self.input_birthday, 5, 5, 1, 1)
        self.label_department = QtWidgets.QLabel(Dialog)
        self.label_department.setObjectName("label_department")
        self.gridLayout_2.addWidget(self.label_department, 0, 0, 1, 1)
        self.input_position = QtWidgets.QComboBox(Dialog)
        self.input_position.setObjectName("input_position")
        self.gridLayout_2.addWidget(self.input_position, 1, 3, 1, 1)
        self.label_position = QtWidgets.QLabel(Dialog)
        self.label_position.setObjectName("label_position")
        self.gridLayout_2.addWidget(self.label_position, 1, 2, 1, 1)
        self.label_postcode = QtWidgets.QLabel(Dialog)
        self.label_postcode.setObjectName("label_postcode")
        self.gridLayout_2.addWidget(self.label_postcode, 4, 4, 1, 1)
        self.input_gender = QtWidgets.QComboBox(Dialog)
        self.input_gender.setObjectName("input_gender")
        self.input_gender.addItem("")
        self.input_gender.addItem("")
        self.gridLayout_2.addWidget(self.input_gender, 2, 3, 1, 1)
        self.label_qq = QtWidgets.QLabel(Dialog)
        self.label_qq.setObjectName("label_qq")
        self.gridLayout_2.addWidget(self.label_qq, 3, 2, 1, 1)
        self.label_phone = QtWidgets.QLabel(Dialog)
        self.label_phone.setObjectName("label_phone")
        self.gridLayout_2.addWidget(self.label_phone, 3, 0, 1, 1)
        self.label_birthplace = QtWidgets.QLabel(Dialog)
        self.label_birthplace.setObjectName("label_birthplace")
        self.gridLayout_2.addWidget(self.label_birthplace, 5, 2, 1, 1)
        self.label_company = QtWidgets.QLabel(Dialog)
        self.label_company.setObjectName("label_company")
        self.gridLayout_2.addWidget(self.label_company, 0, 2, 1, 1)
        self.input_company = QtWidgets.QComboBox(Dialog)
        self.input_company.setObjectName("input_company")
        self.gridLayout_2.addWidget(self.input_company, 0, 3, 1, 1)
        self.label_department_2 = QtWidgets.QLabel(Dialog)
        self.label_department_2.setObjectName("label_department_2")
        self.gridLayout_2.addWidget(self.label_department_2, 0, 4, 1, 1)
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setObjectName("label_name")
        self.gridLayout_2.addWidget(self.label_name, 2, 0, 1, 1)
        self.input_name = QtWidgets.QLineEdit(Dialog)
        self.input_name.setObjectName("input_name")
        self.gridLayout_2.addWidget(self.input_name, 2, 1, 1, 1)
        self.input_positioncat = QtWidgets.QComboBox(Dialog)
        self.input_positioncat.setObjectName("input_positioncat")
        self.gridLayout_2.addWidget(self.input_positioncat, 1, 1, 1, 1)
        self.label_positiontitle = QtWidgets.QLabel(Dialog)
        self.label_positiontitle.setObjectName("label_positiontitle")
        self.gridLayout_2.addWidget(self.label_positiontitle, 1, 4, 1, 1)
        self.label_email = QtWidgets.QLabel(Dialog)
        self.label_email.setObjectName("label_email")
        self.gridLayout_2.addWidget(self.label_email, 2, 4, 1, 1)
        self.label_positioncat = QtWidgets.QLabel(Dialog)
        self.label_positioncat.setObjectName("label_positioncat")
        self.gridLayout_2.addWidget(self.label_positioncat, 1, 0, 1, 1)
        self.input_phone = QtWidgets.QLineEdit(Dialog)
        self.input_phone.setObjectName("input_phone")
        self.gridLayout_2.addWidget(self.input_phone, 3, 1, 1, 1)
        self.label_mobilephone = QtWidgets.QLabel(Dialog)
        self.label_mobilephone.setObjectName("label_mobilephone")
        self.gridLayout_2.addWidget(self.label_mobilephone, 3, 4, 1, 1)
        self.input_group = QtWidgets.QComboBox(Dialog)
        self.input_group.setObjectName("input_group")
        self.gridLayout_2.addWidget(self.input_group, 0, 1, 1, 1)
        self.label_hobby = QtWidgets.QLabel(Dialog)
        self.label_hobby.setObjectName("label_hobby")
        self.gridLayout_2.addWidget(self.label_hobby, 9, 4, 1, 1)
        self.label_education = QtWidgets.QLabel(Dialog)
        self.label_education.setObjectName("label_education")
        self.gridLayout_2.addWidget(self.label_education, 7, 2, 1, 1)
        self.input_booker = QtWidgets.QLineEdit(Dialog)
        self.input_booker.setObjectName("input_booker")
        self.gridLayout_2.addWidget(self.input_booker, 8, 7, 1, 1)
        self.input_vitae = QtWidgets.QTextEdit(Dialog)
        self.input_vitae.setObjectName("input_vitae")
        self.gridLayout_2.addWidget(self.input_vitae, 10, 1, 1, 7)
        self.label_major = QtWidgets.QLabel(Dialog)
        self.label_major.setObjectName("label_major")
        self.gridLayout_2.addWidget(self.label_major, 7, 6, 1, 1)
        self.input_openingbank = QtWidgets.QLineEdit(Dialog)
        self.input_openingbank.setObjectName("input_openingbank")
        self.gridLayout_2.addWidget(self.input_openingbank, 8, 3, 1, 1)
        self.input_salary = QtWidgets.QComboBox(Dialog)
        self.input_salary.setObjectName("input_salary")
        self.gridLayout_2.addWidget(self.input_salary, 8, 1, 1, 1)
        self.label_faith = QtWidgets.QLabel(Dialog)
        self.label_faith.setObjectName("label_faith")
        self.gridLayout_2.addWidget(self.label_faith, 6, 0, 1, 1)
        self.label_ethnicity = QtWidgets.QLabel(Dialog)
        self.label_ethnicity.setObjectName("label_ethnicity")
        self.gridLayout_2.addWidget(self.label_ethnicity, 5, 6, 1, 1)
        self.input_educationtime = QtWidgets.QComboBox(Dialog)
        self.input_educationtime.setObjectName("input_educationtime")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.input_educationtime.addItem("")
        self.gridLayout_2.addWidget(self.input_educationtime, 7, 5, 1, 1)
        self.input_faith = QtWidgets.QComboBox(Dialog)
        self.input_faith.setObjectName("input_faith")
        self.input_faith.addItem("")
        self.input_faith.addItem("")
        self.input_faith.addItem("")
        self.input_faith.addItem("")
        self.input_faith.addItem("")
        self.gridLayout_2.addWidget(self.input_faith, 6, 1, 1, 1)
        self.input_relationship = QtWidgets.QTextEdit(Dialog)
        self.input_relationship.setObjectName("input_relationship")
        self.gridLayout_2.addWidget(self.input_relationship, 11, 1, 1, 7)
        self.label_remarks = QtWidgets.QLabel(Dialog)
        self.label_remarks.setObjectName("label_remarks")
        self.gridLayout_2.addWidget(self.label_remarks, 12, 0, 1, 1)
        self.input_identification = QtWidgets.QLineEdit(Dialog)
        self.input_identification.setObjectName("input_identification")
        self.gridLayout_2.addWidget(self.input_identification, 6, 5, 1, 1)
        self.label_booktime = QtWidgets.QLabel(Dialog)
        self.label_booktime.setObjectName("label_booktime")
        self.gridLayout_2.addWidget(self.label_booktime, 9, 0, 1, 1)
        self.label_identification = QtWidgets.QLabel(Dialog)
        self.label_identification.setObjectName("label_identification")
        self.gridLayout_2.addWidget(self.label_identification, 6, 4, 1, 1)
        self.input_remarks = QtWidgets.QTextEdit(Dialog)
        self.input_remarks.setObjectName("input_remarks")
        self.gridLayout_2.addWidget(self.input_remarks, 12, 1, 1, 7)
        self.input_education = QtWidgets.QComboBox(Dialog)
        self.input_education.setObjectName("input_education")
        self.input_education.addItem("")
        self.input_education.addItem("")
        self.input_education.addItem("")
        self.input_education.addItem("")
        self.input_education.addItem("")
        self.input_education.addItem("")
        self.input_education.addItem("")
        self.gridLayout_2.addWidget(self.input_education, 7, 3, 1, 1)
        self.label_age_data = QtWidgets.QLabel(Dialog)
        self.label_age_data.setObjectName("label_age_data")
        self.gridLayout_2.addWidget(self.label_age_data, 7, 1, 1, 1)
        self.input_hobby = QtWidgets.QLineEdit(Dialog)
        self.input_hobby.setObjectName("input_hobby")
        self.gridLayout_2.addWidget(self.input_hobby, 9, 5, 1, 1)
        self.input_ethnicity = QtWidgets.QComboBox(Dialog)
        self.input_ethnicity.setObjectName("input_ethnicity")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.input_ethnicity.addItem("")
        self.gridLayout_2.addWidget(self.input_ethnicity, 5, 7, 1, 1)
        self.label_educationtime = QtWidgets.QLabel(Dialog)
        self.label_educationtime.setObjectName("label_educationtime")
        self.gridLayout_2.addWidget(self.label_educationtime, 7, 4, 1, 1)
        self.label_openingbank = QtWidgets.QLabel(Dialog)
        self.label_openingbank.setObjectName("label_openingbank")
        self.gridLayout_2.addWidget(self.label_openingbank, 8, 2, 1, 1)
        self.input_politicalstatus = QtWidgets.QComboBox(Dialog)
        self.input_politicalstatus.setObjectName("input_politicalstatus")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.input_politicalstatus.addItem("")
        self.gridLayout_2.addWidget(self.input_politicalstatus, 6, 3, 1, 1)
        self.label_booktime_data = QtWidgets.QLabel(Dialog)
        self.label_booktime_data.setObjectName("label_booktime_data")
        self.gridLayout_2.addWidget(self.label_booktime_data, 9, 1, 1, 1)
        self.label_account = QtWidgets.QLabel(Dialog)
        self.label_account.setObjectName("label_account")
        self.gridLayout_2.addWidget(self.label_account, 8, 4, 1, 1)
        self.input_speciality = QtWidgets.QLineEdit(Dialog)
        self.input_speciality.setObjectName("input_speciality")
        self.gridLayout_2.addWidget(self.input_speciality, 9, 3, 1, 1)
        self.label_age = QtWidgets.QLabel(Dialog)
        self.label_age.setObjectName("label_age")
        self.gridLayout_2.addWidget(self.label_age, 7, 0, 1, 1)
        self.input_account = QtWidgets.QLineEdit(Dialog)
        self.input_account.setObjectName("input_account")
        self.gridLayout_2.addWidget(self.input_account, 8, 5, 1, 1)
        self.label_politicalstatus = QtWidgets.QLabel(Dialog)
        self.label_politicalstatus.setObjectName("label_politicalstatus")
        self.gridLayout_2.addWidget(self.label_politicalstatus, 6, 2, 1, 1)
        self.label_socialsecurity = QtWidgets.QLabel(Dialog)
        self.label_socialsecurity.setObjectName("label_socialsecurity")
        self.gridLayout_2.addWidget(self.label_socialsecurity, 6, 6, 1, 1)
        self.label_salary = QtWidgets.QLabel(Dialog)
        self.label_salary.setObjectName("label_salary")
        self.gridLayout_2.addWidget(self.label_salary, 8, 0, 1, 1)
        self.label_booker = QtWidgets.QLabel(Dialog)
        self.label_booker.setObjectName("label_booker")
        self.gridLayout_2.addWidget(self.label_booker, 8, 6, 1, 1)
        self.label_speciality = QtWidgets.QLabel(Dialog)
        self.label_speciality.setObjectName("label_speciality")
        self.gridLayout_2.addWidget(self.label_speciality, 9, 2, 1, 1)
        self.label_vitae = QtWidgets.QLabel(Dialog)
        self.label_vitae.setObjectName("label_vitae")
        self.gridLayout_2.addWidget(self.label_vitae, 10, 0, 1, 1)
        self.label_relationship = QtWidgets.QLabel(Dialog)
        self.label_relationship.setObjectName("label_relationship")
        self.gridLayout_2.addWidget(self.label_relationship, 11, 0, 1, 1)
        self.input_socialsecurity = QtWidgets.QLineEdit(Dialog)
        self.input_socialsecurity.setObjectName("input_socialsecurity")
        self.gridLayout_2.addWidget(self.input_socialsecurity, 6, 7, 1, 1)
        self.input_email = QtWidgets.QLineEdit(Dialog)
        self.input_email.setObjectName("input_email")
        self.gridLayout_2.addWidget(self.input_email, 2, 5, 1, 2)
        self.input_avatar = QtWidgets.QGraphicsView(Dialog)
        self.input_avatar.setMaximumSize(QtCore.QSize(111, 124))
        self.input_avatar.setObjectName("input_avatar")
        self.gridLayout_2.addWidget(self.input_avatar, 0, 7, 5, 1)
        self.input_department = QtWidgets.QComboBox(Dialog)
        self.input_department.setObjectName("input_department")
        self.gridLayout_2.addWidget(self.input_department, 0, 5, 1, 2)
        self.input_positiontitle = QtWidgets.QComboBox(Dialog)
        self.input_positiontitle.setObjectName("input_positiontitle")
        self.gridLayout_2.addWidget(self.input_positiontitle, 1, 5, 1, 2)
        self.input_postcode = QtWidgets.QLineEdit(Dialog)
        self.input_postcode.setObjectName("input_postcode")
        self.gridLayout_2.addWidget(self.input_postcode, 4, 5, 1, 2)
        self.input_mobilephone = QtWidgets.QLineEdit(Dialog)
        self.input_mobilephone.setObjectName("input_mobilephone")
        self.gridLayout_2.addWidget(self.input_mobilephone, 3, 5, 1, 2)
        self.input_address = QtWidgets.QLineEdit(Dialog)
        self.input_address.setObjectName("input_address")
        self.gridLayout_2.addWidget(self.input_address, 4, 1, 1, 3)
        self.input_major = QtWidgets.QLineEdit(Dialog)
        self.input_major.setObjectName("input_major")
        self.gridLayout_2.addWidget(self.input_major, 7, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.button_submit = QtWidgets.QPushButton(Dialog)
        self.button_submit.setObjectName("button_submit")
        self.horizontalLayout_5.addWidget(self.button_submit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.button_clear = QtWidgets.QPushButton(Dialog)
        self.button_clear.setObjectName("button_clear")
        self.horizontalLayout_5.addWidget(self.button_clear)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.input_group, self.input_company)
        Dialog.setTabOrder(self.input_company, self.input_department)
        Dialog.setTabOrder(self.input_department, self.input_positioncat)
        Dialog.setTabOrder(self.input_positioncat, self.input_position)
        Dialog.setTabOrder(self.input_position, self.input_positiontitle)
        Dialog.setTabOrder(self.input_positiontitle, self.input_name)
        Dialog.setTabOrder(self.input_name, self.input_gender)
        Dialog.setTabOrder(self.input_gender, self.input_email)
        Dialog.setTabOrder(self.input_email, self.input_phone)
        Dialog.setTabOrder(self.input_phone, self.input_qq)
        Dialog.setTabOrder(self.input_qq, self.input_mobilephone)
        Dialog.setTabOrder(self.input_mobilephone, self.input_address)
        Dialog.setTabOrder(self.input_address, self.input_postcode)
        Dialog.setTabOrder(self.input_postcode, self.input_nation)
        Dialog.setTabOrder(self.input_nation, self.input_birthplace)
        Dialog.setTabOrder(self.input_birthplace, self.input_birthday)
        Dialog.setTabOrder(self.input_birthday, self.input_ethnicity)
        Dialog.setTabOrder(self.input_ethnicity, self.input_faith)
        Dialog.setTabOrder(self.input_faith, self.input_politicalstatus)
        Dialog.setTabOrder(self.input_politicalstatus, self.input_identification)
        Dialog.setTabOrder(self.input_identification, self.input_socialsecurity)
        Dialog.setTabOrder(self.input_socialsecurity, self.input_education)
        Dialog.setTabOrder(self.input_education, self.input_educationtime)
        Dialog.setTabOrder(self.input_educationtime, self.input_major)
        Dialog.setTabOrder(self.input_major, self.input_salary)
        Dialog.setTabOrder(self.input_salary, self.input_openingbank)
        Dialog.setTabOrder(self.input_openingbank, self.input_account)
        Dialog.setTabOrder(self.input_account, self.input_booker)
        Dialog.setTabOrder(self.input_booker, self.input_speciality)
        Dialog.setTabOrder(self.input_speciality, self.input_hobby)
        Dialog.setTabOrder(self.input_hobby, self.input_vitae)
        Dialog.setTabOrder(self.input_vitae, self.input_relationship)
        Dialog.setTabOrder(self.input_relationship, self.input_remarks)
        Dialog.setTabOrder(self.input_remarks, self.button_submit)
        Dialog.setTabOrder(self.button_submit, self.button_clear)
        Dialog.setTabOrder(self.button_clear, self.input_avatar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_status.setText(_translate("Dialog", "你正在做的业务是：人力资源--人力资源档案管理--人力资源档案登记"))
        self.label_address.setText(_translate("Dialog", "住址"))
        self.label_nation.setText(_translate("Dialog", "国籍"))
        self.label_gender.setText(_translate("Dialog", "性别"))
        self.input_nation.setItemText(0, _translate("Dialog", "中国"))
        self.input_nation.setItemText(1, _translate("Dialog", "阿尔巴尼亚"))
        self.input_nation.setItemText(2, _translate("Dialog", "阿尔及利亚"))
        self.input_nation.setItemText(3, _translate("Dialog", "阿富汗"))
        self.input_nation.setItemText(4, _translate("Dialog", "阿根廷"))
        self.input_nation.setItemText(5, _translate("Dialog", "阿拉伯联合酋长国"))
        self.input_nation.setItemText(6, _translate("Dialog", "阿鲁巴"))
        self.input_nation.setItemText(7, _translate("Dialog", "阿曼"))
        self.input_nation.setItemText(8, _translate("Dialog", "阿塞拜疆"))
        self.input_nation.setItemText(9, _translate("Dialog", "阿森松岛"))
        self.input_nation.setItemText(10, _translate("Dialog", "埃及"))
        self.input_nation.setItemText(11, _translate("Dialog", "埃塞俄比亚"))
        self.input_nation.setItemText(12, _translate("Dialog", "爱尔兰"))
        self.input_nation.setItemText(13, _translate("Dialog", "爱沙尼亚"))
        self.input_nation.setItemText(14, _translate("Dialog", "安道尔"))
        self.input_nation.setItemText(15, _translate("Dialog", "安哥拉"))
        self.input_nation.setItemText(16, _translate("Dialog", "安圭拉"))
        self.input_nation.setItemText(17, _translate("Dialog", "安提瓜岛和巴布达"))
        self.input_nation.setItemText(18, _translate("Dialog", "澳大利亚"))
        self.input_nation.setItemText(19, _translate("Dialog", "奥地利"))
        self.input_nation.setItemText(20, _translate("Dialog", "奥兰群岛"))
        self.input_nation.setItemText(21, _translate("Dialog", "巴巴多斯岛"))
        self.input_nation.setItemText(22, _translate("Dialog", "巴布亚新几内亚"))
        self.input_nation.setItemText(23, _translate("Dialog", "巴哈马"))
        self.input_nation.setItemText(24, _translate("Dialog", "巴基斯坦"))
        self.input_nation.setItemText(25, _translate("Dialog", "巴拉圭"))
        self.input_nation.setItemText(26, _translate("Dialog", "巴勒斯坦"))
        self.input_nation.setItemText(27, _translate("Dialog", "巴林"))
        self.input_nation.setItemText(28, _translate("Dialog", "巴拿马"))
        self.input_nation.setItemText(29, _translate("Dialog", "巴西"))
        self.input_nation.setItemText(30, _translate("Dialog", "白俄罗斯"))
        self.input_nation.setItemText(31, _translate("Dialog", "百慕大"))
        self.input_nation.setItemText(32, _translate("Dialog", "保加利亚"))
        self.input_nation.setItemText(33, _translate("Dialog", "北马里亚纳群岛"))
        self.input_nation.setItemText(34, _translate("Dialog", "贝宁"))
        self.input_nation.setItemText(35, _translate("Dialog", "比利时"))
        self.input_nation.setItemText(36, _translate("Dialog", "冰岛"))
        self.input_nation.setItemText(37, _translate("Dialog", "波多黎各"))
        self.input_nation.setItemText(38, _translate("Dialog", "波兰"))
        self.input_nation.setItemText(39, _translate("Dialog", "玻利维亚"))
        self.input_nation.setItemText(40, _translate("Dialog", "波斯尼亚和黑塞哥维那"))
        self.input_nation.setItemText(41, _translate("Dialog", "博茨瓦纳"))
        self.input_nation.setItemText(42, _translate("Dialog", "伯利兹"))
        self.input_nation.setItemText(43, _translate("Dialog", "不丹"))
        self.input_nation.setItemText(44, _translate("Dialog", "布基纳法索"))
        self.input_nation.setItemText(45, _translate("Dialog", "布隆迪"))
        self.input_nation.setItemText(46, _translate("Dialog", "布韦岛"))
        self.input_nation.setItemText(47, _translate("Dialog", "朝鲜"))
        self.input_nation.setItemText(48, _translate("Dialog", "丹麦"))
        self.input_nation.setItemText(49, _translate("Dialog", "德国"))
        self.input_nation.setItemText(50, _translate("Dialog", "东帝汶"))
        self.input_nation.setItemText(51, _translate("Dialog", "多哥"))
        self.input_nation.setItemText(52, _translate("Dialog", "多米尼加"))
        self.input_nation.setItemText(53, _translate("Dialog", "多米尼加共和国"))
        self.input_nation.setItemText(54, _translate("Dialog", "俄罗斯"))
        self.input_nation.setItemText(55, _translate("Dialog", "厄瓜多尔"))
        self.input_nation.setItemText(56, _translate("Dialog", "厄立特里亚"))
        self.input_nation.setItemText(57, _translate("Dialog", "法国"))
        self.input_nation.setItemText(58, _translate("Dialog", "法罗群岛"))
        self.input_nation.setItemText(59, _translate("Dialog", "法属波利尼西亚"))
        self.input_nation.setItemText(60, _translate("Dialog", "法属圭亚那"))
        self.input_nation.setItemText(61, _translate("Dialog", "法属南部领地"))
        self.input_nation.setItemText(62, _translate("Dialog", "梵蒂冈"))
        self.input_nation.setItemText(63, _translate("Dialog", "菲律宾"))
        self.input_nation.setItemText(64, _translate("Dialog", "斐济"))
        self.input_nation.setItemText(65, _translate("Dialog", "芬兰"))
        self.input_nation.setItemText(66, _translate("Dialog", "佛得角"))
        self.input_nation.setItemText(67, _translate("Dialog", "弗兰克群岛"))
        self.input_nation.setItemText(68, _translate("Dialog", "冈比亚"))
        self.input_nation.setItemText(69, _translate("Dialog", "刚果"))
        self.input_nation.setItemText(70, _translate("Dialog", "刚果民主共和国"))
        self.input_nation.setItemText(71, _translate("Dialog", "哥伦比亚"))
        self.input_nation.setItemText(72, _translate("Dialog", "哥斯达黎加"))
        self.input_nation.setItemText(73, _translate("Dialog", "格恩西岛"))
        self.input_nation.setItemText(74, _translate("Dialog", "格林纳达"))
        self.input_nation.setItemText(75, _translate("Dialog", "格陵兰"))
        self.input_nation.setItemText(76, _translate("Dialog", "古巴"))
        self.input_nation.setItemText(77, _translate("Dialog", "瓜德罗普"))
        self.input_nation.setItemText(78, _translate("Dialog", "关岛"))
        self.input_nation.setItemText(79, _translate("Dialog", "圭亚那"))
        self.input_nation.setItemText(80, _translate("Dialog", "哈萨克斯坦"))
        self.input_nation.setItemText(81, _translate("Dialog", "海地"))
        self.input_nation.setItemText(82, _translate("Dialog", "韩国"))
        self.input_nation.setItemText(83, _translate("Dialog", "荷兰"))
        self.input_nation.setItemText(84, _translate("Dialog", "荷属安地列斯"))
        self.input_nation.setItemText(85, _translate("Dialog", "赫德和麦克唐纳群岛"))
        self.input_nation.setItemText(86, _translate("Dialog", "洪都拉斯"))
        self.input_nation.setItemText(87, _translate("Dialog", "基里巴斯"))
        self.input_nation.setItemText(88, _translate("Dialog", "吉布提"))
        self.input_nation.setItemText(89, _translate("Dialog", "吉尔吉斯斯坦"))
        self.input_nation.setItemText(90, _translate("Dialog", "几内亚"))
        self.input_nation.setItemText(91, _translate("Dialog", "几内亚比绍"))
        self.input_nation.setItemText(92, _translate("Dialog", "加拿大"))
        self.input_nation.setItemText(93, _translate("Dialog", "加纳"))
        self.input_nation.setItemText(94, _translate("Dialog", "加蓬"))
        self.input_nation.setItemText(95, _translate("Dialog", "柬埔寨"))
        self.input_nation.setItemText(96, _translate("Dialog", "捷克共和国"))
        self.input_nation.setItemText(97, _translate("Dialog", "津巴布韦"))
        self.input_nation.setItemText(98, _translate("Dialog", "喀麦隆"))
        self.input_nation.setItemText(99, _translate("Dialog", "卡塔尔"))
        self.input_nation.setItemText(100, _translate("Dialog", "开曼群岛"))
        self.input_nation.setItemText(101, _translate("Dialog", "科科斯群岛"))
        self.input_nation.setItemText(102, _translate("Dialog", "科摩罗"))
        self.input_nation.setItemText(103, _translate("Dialog", "科特迪瓦"))
        self.input_nation.setItemText(104, _translate("Dialog", "科威特"))
        self.input_nation.setItemText(105, _translate("Dialog", "克罗地亚"))
        self.input_nation.setItemText(106, _translate("Dialog", "肯尼亚"))
        self.input_nation.setItemText(107, _translate("Dialog", "库克群岛"))
        self.input_nation.setItemText(108, _translate("Dialog", "拉脱维亚"))
        self.input_nation.setItemText(109, _translate("Dialog", "莱索托"))
        self.input_nation.setItemText(110, _translate("Dialog", "老挝"))
        self.input_nation.setItemText(111, _translate("Dialog", "黎巴嫩"))
        self.input_nation.setItemText(112, _translate("Dialog", "利比里亚"))
        self.input_nation.setItemText(113, _translate("Dialog", "利比亚"))
        self.input_nation.setItemText(114, _translate("Dialog", "立陶宛"))
        self.input_nation.setItemText(115, _translate("Dialog", "列支敦士登"))
        self.input_nation.setItemText(116, _translate("Dialog", "留尼旺岛"))
        self.input_nation.setItemText(117, _translate("Dialog", "卢森堡"))
        self.input_nation.setItemText(118, _translate("Dialog", "卢旺达"))
        self.input_nation.setItemText(119, _translate("Dialog", "罗马尼亚"))
        self.input_nation.setItemText(120, _translate("Dialog", "马达加斯加"))
        self.input_nation.setItemText(121, _translate("Dialog", "马尔代夫"))
        self.input_nation.setItemText(122, _translate("Dialog", "马耳他"))
        self.input_nation.setItemText(123, _translate("Dialog", "马拉维"))
        self.input_nation.setItemText(124, _translate("Dialog", "马来西亚"))
        self.input_nation.setItemText(125, _translate("Dialog", "马里"))
        self.input_nation.setItemText(126, _translate("Dialog", "马其顿"))
        self.input_nation.setItemText(127, _translate("Dialog", "马绍尔群岛"))
        self.input_nation.setItemText(128, _translate("Dialog", "马提尼克"))
        self.input_nation.setItemText(129, _translate("Dialog", "马约特岛"))
        self.input_nation.setItemText(130, _translate("Dialog", "曼岛"))
        self.input_nation.setItemText(131, _translate("Dialog", "毛里求斯"))
        self.input_nation.setItemText(132, _translate("Dialog", "毛里塔尼亚"))
        self.input_nation.setItemText(133, _translate("Dialog", "美国"))
        self.input_nation.setItemText(134, _translate("Dialog", "美属萨摩亚"))
        self.input_nation.setItemText(135, _translate("Dialog", "美属外岛"))
        self.input_nation.setItemText(136, _translate("Dialog", "蒙古"))
        self.input_nation.setItemText(137, _translate("Dialog", "蒙特塞拉特"))
        self.input_nation.setItemText(138, _translate("Dialog", "孟加拉"))
        self.input_nation.setItemText(139, _translate("Dialog", "密克罗尼西亚"))
        self.input_nation.setItemText(140, _translate("Dialog", "秘鲁"))
        self.input_nation.setItemText(141, _translate("Dialog", "缅甸"))
        self.input_nation.setItemText(142, _translate("Dialog", "摩尔多瓦"))
        self.input_nation.setItemText(143, _translate("Dialog", "摩洛哥"))
        self.input_nation.setItemText(144, _translate("Dialog", "摩纳哥"))
        self.input_nation.setItemText(145, _translate("Dialog", "莫桑比克"))
        self.input_nation.setItemText(146, _translate("Dialog", "墨西哥"))
        self.input_nation.setItemText(147, _translate("Dialog", "纳米比亚"))
        self.input_nation.setItemText(148, _translate("Dialog", "南非"))
        self.input_nation.setItemText(149, _translate("Dialog", "南极洲"))
        self.input_nation.setItemText(150, _translate("Dialog", "南乔治亚和南桑德威奇群岛"))
        self.input_nation.setItemText(151, _translate("Dialog", "瑙鲁"))
        self.input_nation.setItemText(152, _translate("Dialog", "尼泊尔"))
        self.input_nation.setItemText(153, _translate("Dialog", "尼加拉瓜"))
        self.input_nation.setItemText(154, _translate("Dialog", "尼日尔"))
        self.input_nation.setItemText(155, _translate("Dialog", "尼日利亚"))
        self.input_nation.setItemText(156, _translate("Dialog", "纽埃"))
        self.input_nation.setItemText(157, _translate("Dialog", "挪威"))
        self.input_nation.setItemText(158, _translate("Dialog", "诺福克"))
        self.input_nation.setItemText(159, _translate("Dialog", "帕劳群岛"))
        self.input_nation.setItemText(160, _translate("Dialog", "皮特凯恩"))
        self.input_nation.setItemText(161, _translate("Dialog", "葡萄牙"))
        self.input_nation.setItemText(162, _translate("Dialog", "乔治亚"))
        self.input_nation.setItemText(163, _translate("Dialog", "日本"))
        self.input_nation.setItemText(164, _translate("Dialog", "瑞典"))
        self.input_nation.setItemText(165, _translate("Dialog", "瑞士"))
        self.input_nation.setItemText(166, _translate("Dialog", "萨尔瓦多"))
        self.input_nation.setItemText(167, _translate("Dialog", "萨摩亚"))
        self.input_nation.setItemText(168, _translate("Dialog", "塞拉利昂"))
        self.input_nation.setItemText(169, _translate("Dialog", "塞内加尔"))
        self.input_nation.setItemText(170, _translate("Dialog", "塞浦路斯"))
        self.input_nation.setItemText(171, _translate("Dialog", "塞舌尔"))
        self.input_nation.setItemText(172, _translate("Dialog", "沙特阿拉伯"))
        self.input_nation.setItemText(173, _translate("Dialog", "圣诞岛"))
        self.input_nation.setItemText(174, _translate("Dialog", "圣多美和普林西比"))
        self.input_nation.setItemText(175, _translate("Dialog", "圣赫勒拿"))
        self.input_nation.setItemText(176, _translate("Dialog", "圣基茨和尼维斯"))
        self.input_nation.setItemText(177, _translate("Dialog", "圣卢西亚"))
        self.input_nation.setItemText(178, _translate("Dialog", "圣马力诺"))
        self.input_nation.setItemText(179, _translate("Dialog", "圣皮埃尔和米克隆群岛"))
        self.input_nation.setItemText(180, _translate("Dialog", "圣文森特和格林纳丁斯"))
        self.input_nation.setItemText(181, _translate("Dialog", "斯里兰卡"))
        self.input_nation.setItemText(182, _translate("Dialog", "斯洛伐克"))
        self.input_nation.setItemText(183, _translate("Dialog", "斯洛文尼亚"))
        self.input_nation.setItemText(184, _translate("Dialog", "斯瓦尔巴和扬马廷"))
        self.input_nation.setItemText(185, _translate("Dialog", "斯威士兰"))
        self.input_nation.setItemText(186, _translate("Dialog", "苏丹"))
        self.input_nation.setItemText(187, _translate("Dialog", "苏里南"))
        self.input_nation.setItemText(188, _translate("Dialog", "所罗门群岛"))
        self.input_nation.setItemText(189, _translate("Dialog", "索马里"))
        self.input_nation.setItemText(190, _translate("Dialog", "塔吉克斯坦"))
        self.input_nation.setItemText(191, _translate("Dialog", "泰国"))
        self.input_nation.setItemText(192, _translate("Dialog", "坦桑尼亚"))
        self.input_nation.setItemText(193, _translate("Dialog", "汤加"))
        self.input_nation.setItemText(194, _translate("Dialog", "特克斯和凯克特斯群岛"))
        self.input_nation.setItemText(195, _translate("Dialog", "特里斯坦达昆哈"))
        self.input_nation.setItemText(196, _translate("Dialog", "特立尼达和多巴哥"))
        self.input_nation.setItemText(197, _translate("Dialog", "突尼斯"))
        self.input_nation.setItemText(198, _translate("Dialog", "图瓦卢"))
        self.input_nation.setItemText(199, _translate("Dialog", "土耳其"))
        self.input_nation.setItemText(200, _translate("Dialog", "土库曼斯坦"))
        self.input_nation.setItemText(201, _translate("Dialog", "托克劳"))
        self.input_nation.setItemText(202, _translate("Dialog", "瓦利斯和福图纳"))
        self.input_nation.setItemText(203, _translate("Dialog", "瓦努阿图"))
        self.input_nation.setItemText(204, _translate("Dialog", "危地马拉"))
        self.input_nation.setItemText(205, _translate("Dialog", "委内瑞拉"))
        self.input_nation.setItemText(206, _translate("Dialog", "文莱"))
        self.input_nation.setItemText(207, _translate("Dialog", "乌干达"))
        self.input_nation.setItemText(208, _translate("Dialog", "乌克兰"))
        self.input_nation.setItemText(209, _translate("Dialog", "乌拉圭"))
        self.input_nation.setItemText(210, _translate("Dialog", "乌兹别克斯坦"))
        self.input_nation.setItemText(211, _translate("Dialog", "西班牙"))
        self.input_nation.setItemText(212, _translate("Dialog", "希腊"))
        self.input_nation.setItemText(213, _translate("Dialog", "新加坡"))
        self.input_nation.setItemText(214, _translate("Dialog", "新喀里多尼亚"))
        self.input_nation.setItemText(215, _translate("Dialog", "新西兰"))
        self.input_nation.setItemText(216, _translate("Dialog", "匈牙利"))
        self.input_nation.setItemText(217, _translate("Dialog", "叙利亚"))
        self.input_nation.setItemText(218, _translate("Dialog", "牙买加"))
        self.input_nation.setItemText(219, _translate("Dialog", "亚美尼亚"))
        self.input_nation.setItemText(220, _translate("Dialog", "也门"))
        self.input_nation.setItemText(221, _translate("Dialog", "伊拉克"))
        self.input_nation.setItemText(222, _translate("Dialog", "伊朗"))
        self.input_nation.setItemText(223, _translate("Dialog", "以色列"))
        self.input_nation.setItemText(224, _translate("Dialog", "意大利"))
        self.input_nation.setItemText(225, _translate("Dialog", "印度"))
        self.input_nation.setItemText(226, _translate("Dialog", "印度尼西亚"))
        self.input_nation.setItemText(227, _translate("Dialog", "英国"))
        self.input_nation.setItemText(228, _translate("Dialog", "英属印度洋领地"))
        self.input_nation.setItemText(229, _translate("Dialog", "约旦"))
        self.input_nation.setItemText(230, _translate("Dialog", "越南"))
        self.input_nation.setItemText(231, _translate("Dialog", "赞比亚"))
        self.input_nation.setItemText(232, _translate("Dialog", "泽西岛"))
        self.input_nation.setItemText(233, _translate("Dialog", "乍得"))
        self.input_nation.setItemText(234, _translate("Dialog", "直布罗陀"))
        self.input_nation.setItemText(235, _translate("Dialog", "智利"))
        self.input_nation.setItemText(236, _translate("Dialog", "中非共和国"))
        self.label_birthday.setText(_translate("Dialog", "生日"))
        self.label_department.setText(_translate("Dialog", "I级机构"))
        self.label_position.setText(_translate("Dialog", "职位名称"))
        self.label_postcode.setText(_translate("Dialog", "邮编"))
        self.input_gender.setItemText(0, _translate("Dialog", "男"))
        self.input_gender.setItemText(1, _translate("Dialog", "女"))
        self.label_qq.setText(_translate("Dialog", "qq"))
        self.label_phone.setText(_translate("Dialog", "电话"))
        self.label_birthplace.setText(_translate("Dialog", "出生地"))
        self.label_company.setText(_translate("Dialog", "II级机构"))
        self.label_department_2.setText(_translate("Dialog", "III级机构"))
        self.label_name.setText(_translate("Dialog", "姓名"))
        self.label_positiontitle.setText(_translate("Dialog", "职称"))
        self.label_email.setText(_translate("Dialog", "电子邮箱"))
        self.label_positioncat.setText(_translate("Dialog", "职位分类"))
        self.label_mobilephone.setText(_translate("Dialog", "手机"))
        self.label_hobby.setText(_translate("Dialog", "爱好"))
        self.label_education.setText(_translate("Dialog", "学历"))
        self.label_major.setText(_translate("Dialog", "学历专业"))
        self.label_faith.setText(_translate("Dialog", "宗教信仰"))
        self.label_ethnicity.setText(_translate("Dialog", "民族"))
        self.input_educationtime.setItemText(0, _translate("Dialog", "0"))
        self.input_educationtime.setItemText(1, _translate("Dialog", "1"))
        self.input_educationtime.setItemText(2, _translate("Dialog", "2"))
        self.input_educationtime.setItemText(3, _translate("Dialog", "3"))
        self.input_educationtime.setItemText(4, _translate("Dialog", "4"))
        self.input_educationtime.setItemText(5, _translate("Dialog", "5"))
        self.input_educationtime.setItemText(6, _translate("Dialog", "6"))
        self.input_educationtime.setItemText(7, _translate("Dialog", "7"))
        self.input_educationtime.setItemText(8, _translate("Dialog", "8"))
        self.input_educationtime.setItemText(9, _translate("Dialog", "9"))
        self.input_educationtime.setItemText(10, _translate("Dialog", "10"))
        self.input_educationtime.setItemText(11, _translate("Dialog", "11"))
        self.input_educationtime.setItemText(12, _translate("Dialog", "12"))
        self.input_educationtime.setItemText(13, _translate("Dialog", "13"))
        self.input_educationtime.setItemText(14, _translate("Dialog", "14"))
        self.input_educationtime.setItemText(15, _translate("Dialog", "15"))
        self.input_educationtime.setItemText(16, _translate("Dialog", "16"))
        self.input_educationtime.setItemText(17, _translate("Dialog", "17"))
        self.input_educationtime.setItemText(18, _translate("Dialog", "18"))
        self.input_educationtime.setItemText(19, _translate("Dialog", "19"))
        self.input_educationtime.setItemText(20, _translate("Dialog", "20"))
        self.input_educationtime.setItemText(21, _translate("Dialog", "21"))
        self.input_educationtime.setItemText(22, _translate("Dialog", "22"))
        self.input_educationtime.setItemText(23, _translate("Dialog", "23"))
        self.input_educationtime.setItemText(24, _translate("Dialog", "24"))
        self.input_faith.setItemText(0, _translate("Dialog", "无"))
        self.input_faith.setItemText(1, _translate("Dialog", "基督教"))
        self.input_faith.setItemText(2, _translate("Dialog", "伊斯兰教"))
        self.input_faith.setItemText(3, _translate("Dialog", "佛教"))
        self.input_faith.setItemText(4, _translate("Dialog", "其他"))
        self.label_remarks.setText(_translate("Dialog", "备注"))
        self.label_booktime.setText(_translate("Dialog", "建档时间"))
        self.label_identification.setText(_translate("Dialog", "身份证号码"))
        self.input_education.setItemText(0, _translate("Dialog", "小学"))
        self.input_education.setItemText(1, _translate("Dialog", "初中"))
        self.input_education.setItemText(2, _translate("Dialog", "高中"))
        self.input_education.setItemText(3, _translate("Dialog", "大学专科"))
        self.input_education.setItemText(4, _translate("Dialog", "大学本科"))
        self.input_education.setItemText(5, _translate("Dialog", "硕士研究生"))
        self.input_education.setItemText(6, _translate("Dialog", "博士研究生"))
        self.label_age_data.setText(_translate("Dialog", "0"))
        self.input_ethnicity.setItemText(0, _translate("Dialog", "汉族"))
        self.input_ethnicity.setItemText(1, _translate("Dialog", "蒙古族"))
        self.input_ethnicity.setItemText(2, _translate("Dialog", "回族"))
        self.input_ethnicity.setItemText(3, _translate("Dialog", "藏族"))
        self.input_ethnicity.setItemText(4, _translate("Dialog", "维吾尔族"))
        self.input_ethnicity.setItemText(5, _translate("Dialog", "苗族"))
        self.input_ethnicity.setItemText(6, _translate("Dialog", "彝族"))
        self.input_ethnicity.setItemText(7, _translate("Dialog", "壮族"))
        self.input_ethnicity.setItemText(8, _translate("Dialog", "布依族"))
        self.input_ethnicity.setItemText(9, _translate("Dialog", "朝鲜族"))
        self.input_ethnicity.setItemText(10, _translate("Dialog", "满族"))
        self.input_ethnicity.setItemText(11, _translate("Dialog", "侗族"))
        self.input_ethnicity.setItemText(12, _translate("Dialog", "瑶族"))
        self.input_ethnicity.setItemText(13, _translate("Dialog", "白族"))
        self.input_ethnicity.setItemText(14, _translate("Dialog", "土家族"))
        self.input_ethnicity.setItemText(15, _translate("Dialog", "哈尼族"))
        self.input_ethnicity.setItemText(16, _translate("Dialog", "哈萨克族"))
        self.input_ethnicity.setItemText(17, _translate("Dialog", "傣族"))
        self.input_ethnicity.setItemText(18, _translate("Dialog", "黎族"))
        self.input_ethnicity.setItemText(19, _translate("Dialog", "僳僳族"))
        self.input_ethnicity.setItemText(20, _translate("Dialog", "佤族"))
        self.input_ethnicity.setItemText(21, _translate("Dialog", "畲族"))
        self.input_ethnicity.setItemText(22, _translate("Dialog", "高山族"))
        self.input_ethnicity.setItemText(23, _translate("Dialog", "拉祜族"))
        self.input_ethnicity.setItemText(24, _translate("Dialog", "水族"))
        self.input_ethnicity.setItemText(25, _translate("Dialog", "东乡族"))
        self.input_ethnicity.setItemText(26, _translate("Dialog", "纳西族"))
        self.input_ethnicity.setItemText(27, _translate("Dialog", "景颇族"))
        self.input_ethnicity.setItemText(28, _translate("Dialog", "柯尔克孜族"))
        self.input_ethnicity.setItemText(29, _translate("Dialog", "土族"))
        self.input_ethnicity.setItemText(30, _translate("Dialog", "达斡尔族"))
        self.input_ethnicity.setItemText(31, _translate("Dialog", "仫佬族"))
        self.input_ethnicity.setItemText(32, _translate("Dialog", "羌族"))
        self.input_ethnicity.setItemText(33, _translate("Dialog", "布朗族"))
        self.input_ethnicity.setItemText(34, _translate("Dialog", "撒拉族"))
        self.input_ethnicity.setItemText(35, _translate("Dialog", "毛南族"))
        self.input_ethnicity.setItemText(36, _translate("Dialog", "仡佬族"))
        self.input_ethnicity.setItemText(37, _translate("Dialog", "锡伯族"))
        self.input_ethnicity.setItemText(38, _translate("Dialog", "阿昌族"))
        self.input_ethnicity.setItemText(39, _translate("Dialog", "普米族"))
        self.input_ethnicity.setItemText(40, _translate("Dialog", "塔吉克族"))
        self.input_ethnicity.setItemText(41, _translate("Dialog", "怒族"))
        self.input_ethnicity.setItemText(42, _translate("Dialog", "乌孜别克族"))
        self.input_ethnicity.setItemText(43, _translate("Dialog", "俄罗斯族"))
        self.input_ethnicity.setItemText(44, _translate("Dialog", "鄂温克族"))
        self.input_ethnicity.setItemText(45, _translate("Dialog", "德昂族"))
        self.input_ethnicity.setItemText(46, _translate("Dialog", "保安族"))
        self.input_ethnicity.setItemText(47, _translate("Dialog", "裕固族"))
        self.input_ethnicity.setItemText(48, _translate("Dialog", "京族"))
        self.input_ethnicity.setItemText(49, _translate("Dialog", "塔塔尔族"))
        self.input_ethnicity.setItemText(50, _translate("Dialog", "独龙族"))
        self.input_ethnicity.setItemText(51, _translate("Dialog", "鄂伦春族"))
        self.input_ethnicity.setItemText(52, _translate("Dialog", "赫哲族"))
        self.input_ethnicity.setItemText(53, _translate("Dialog", "门巴族"))
        self.input_ethnicity.setItemText(54, _translate("Dialog", "珞巴族"))
        self.input_ethnicity.setItemText(55, _translate("Dialog", "基诺族"))
        self.label_educationtime.setText(_translate("Dialog", "教育年限"))
        self.label_openingbank.setText(_translate("Dialog", "开户行"))
        self.input_politicalstatus.setItemText(0, _translate("Dialog", "中共党员"))
        self.input_politicalstatus.setItemText(1, _translate("Dialog", "中共预备党员"))
        self.input_politicalstatus.setItemText(2, _translate("Dialog", "共青团员"))
        self.input_politicalstatus.setItemText(3, _translate("Dialog", "民革党员"))
        self.input_politicalstatus.setItemText(4, _translate("Dialog", "民盟盟员"))
        self.input_politicalstatus.setItemText(5, _translate("Dialog", "民建会员"))
        self.input_politicalstatus.setItemText(6, _translate("Dialog", "民进会员"))
        self.input_politicalstatus.setItemText(7, _translate("Dialog", "农工党党员"))
        self.input_politicalstatus.setItemText(8, _translate("Dialog", "致公党党员"))
        self.input_politicalstatus.setItemText(9, _translate("Dialog", "九三学社社员"))
        self.input_politicalstatus.setItemText(10, _translate("Dialog", "台盟盟员"))
        self.input_politicalstatus.setItemText(11, _translate("Dialog", "无党派人士"))
        self.input_politicalstatus.setItemText(12, _translate("Dialog", "群众"))
        self.label_booktime_data.setText(_translate("Dialog", "datetime"))
        self.label_account.setText(_translate("Dialog", "账号"))
        self.label_age.setText(_translate("Dialog", "年龄"))
        self.label_politicalstatus.setText(_translate("Dialog", "政治面貌"))
        self.label_socialsecurity.setText(_translate("Dialog", "社会保障号码"))
        self.label_salary.setText(_translate("Dialog", "薪酬标准"))
        self.label_booker.setText(_translate("Dialog", "登记人"))
        self.label_speciality.setText(_translate("Dialog", "特长"))
        self.label_vitae.setText(_translate("Dialog", "个人履历"))
        self.label_relationship.setText(_translate("Dialog", "家庭关系信息"))
        self.button_submit.setText(_translate("Dialog", "提交"))
        self.button_clear.setText(_translate("Dialog", "清除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

