# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Python\HRM\main\Ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 121))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 2, 3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(70, 40, 131, 171))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.graphicsView_22 = QtWidgets.QGraphicsView(self.frame_4)
        self.graphicsView_22.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_22.setObjectName("graphicsView_22")
        self.button_query = QtWidgets.QPushButton(self.frame_4)
        self.button_query.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.button_query.setObjectName("button_query")
        self.frame_5 = QtWidgets.QFrame(self.tab_3)
        self.frame_5.setGeometry(QtCore.QRect(230, 40, 131, 171))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.graphicsView_24 = QtWidgets.QGraphicsView(self.frame_5)
        self.graphicsView_24.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_24.setObjectName("graphicsView_24")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_6 = QtWidgets.QFrame(self.tab_3)
        self.frame_6.setGeometry(QtCore.QRect(390, 40, 131, 171))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.graphicsView_25 = QtWidgets.QGraphicsView(self.frame_6)
        self.graphicsView_25.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_25.setObjectName("graphicsView_25")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_7 = QtWidgets.QFrame(self.tab_3)
        self.frame_7.setGeometry(QtCore.QRect(550, 40, 131, 171))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.graphicsView_26 = QtWidgets.QGraphicsView(self.frame_7)
        self.graphicsView_26.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_26.setObjectName("graphicsView_26")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_8 = QtWidgets.QFrame(self.tab_3)
        self.frame_8.setGeometry(QtCore.QRect(70, 240, 131, 171))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.graphicsView_27 = QtWidgets.QGraphicsView(self.frame_8)
        self.graphicsView_27.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_27.setObjectName("graphicsView_27")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_9 = QtWidgets.QFrame(self.tab_3)
        self.frame_9.setGeometry(QtCore.QRect(230, 240, 131, 171))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.graphicsView_30 = QtWidgets.QGraphicsView(self.frame_9)
        self.graphicsView_30.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_30.setObjectName("graphicsView_30")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.frame_10 = QtWidgets.QFrame(self.tab_3)
        self.frame_10.setGeometry(QtCore.QRect(390, 240, 131, 171))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.graphicsView_32 = QtWidgets.QGraphicsView(self.frame_10)
        self.graphicsView_32.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_32.setObjectName("graphicsView_32")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.frame_11 = QtWidgets.QFrame(self.tab_3)
        self.frame_11.setGeometry(QtCore.QRect(550, 240, 131, 171))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.graphicsView_33 = QtWidgets.QGraphicsView(self.frame_11)
        self.graphicsView_33.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_33.setObjectName("graphicsView_33")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_12 = QtWidgets.QFrame(self.tab_4)
        self.frame_12.setGeometry(QtCore.QRect(70, 40, 131, 171))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.graphicsView_34 = QtWidgets.QGraphicsView(self.frame_12)
        self.graphicsView_34.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_34.setObjectName("graphicsView_34")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.frame_13 = QtWidgets.QFrame(self.tab_4)
        self.frame_13.setGeometry(QtCore.QRect(230, 40, 131, 171))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.graphicsView_35 = QtWidgets.QGraphicsView(self.frame_13)
        self.graphicsView_35.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_35.setObjectName("graphicsView_35")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.frame_14 = QtWidgets.QFrame(self.tab_4)
        self.frame_14.setGeometry(QtCore.QRect(390, 40, 131, 171))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.graphicsView_36 = QtWidgets.QGraphicsView(self.frame_14)
        self.graphicsView_36.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_36.setObjectName("graphicsView_36")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.frame_15 = QtWidgets.QFrame(self.tab_4)
        self.frame_15.setGeometry(QtCore.QRect(550, 40, 131, 171))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.graphicsView_37 = QtWidgets.QGraphicsView(self.frame_15)
        self.graphicsView_37.setGeometry(QtCore.QRect(0, 0, 131, 121))
        self.graphicsView_37.setObjectName("graphicsView_37")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(592, 70, 105, 60))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(703, 70, 88, 60))
        self.label_10.setObjectName("label_10")
        self.graphicsView.raise_()
        self.label_10.raise_()
        self.label_9.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_query.setText(_translate("MainWindow", "人事查询"))
        self.pushButton_3.setText(_translate("MainWindow", "人事登记"))
        self.pushButton_4.setText(_translate("MainWindow", "人事变更"))
        self.pushButton_5.setText(_translate("MainWindow", "人事复核"))
        self.pushButton_6.setText(_translate("MainWindow", "人事类别"))
        self.pushButton_9.setText(_translate("MainWindow", "人事XX"))
        self.pushButton_11.setText(_translate("MainWindow", "人事YY"))
        self.pushButton_12.setText(_translate("MainWindow", "人事删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.pushButton_13.setText(_translate("MainWindow", "机构查询"))
        self.pushButton_14.setText(_translate("MainWindow", "机构登记"))
        self.pushButton_15.setText(_translate("MainWindow", "机构变更"))
        self.pushButton_16.setText(_translate("MainWindow", "机构删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "页"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">当前登陆用户：</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">currentUser</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

