# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Python\HRM\main\Ui\permission.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(336, 554)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.input_name = QtWidgets.QLineEdit(Dialog)
        self.input_name.setObjectName("input_name")
        self.gridLayout.addWidget(self.input_name, 1, 2, 1, 1)
        self.check_HUMAN_CREATE = QtWidgets.QCheckBox(Dialog)
        self.check_HUMAN_CREATE.setObjectName("check_HUMAN_CREATE")
        self.gridLayout.addWidget(self.check_HUMAN_CREATE, 4, 2, 1, 1)
        self.check_INSTITUTE_DELETE = QtWidgets.QCheckBox(Dialog)
        self.check_INSTITUTE_DELETE.setObjectName("check_INSTITUTE_DELETE")
        self.gridLayout.addWidget(self.check_INSTITUTE_DELETE, 12, 2, 1, 1)
        self.check_SALARY_CREATE = QtWidgets.QCheckBox(Dialog)
        self.check_SALARY_CREATE.setObjectName("check_SALARY_CREATE")
        self.gridLayout.addWidget(self.check_SALARY_CREATE, 14, 2, 1, 1)
        self.check_INSTITUTE_CONFIRM = QtWidgets.QCheckBox(Dialog)
        self.check_INSTITUTE_CONFIRM.setObjectName("check_INSTITUTE_CONFIRM")
        self.gridLayout.addWidget(self.check_INSTITUTE_CONFIRM, 11, 2, 1, 1)
        self.check_HUMAN_UPDATE = QtWidgets.QCheckBox(Dialog)
        self.check_HUMAN_UPDATE.setObjectName("check_HUMAN_UPDATE")
        self.gridLayout.addWidget(self.check_HUMAN_UPDATE, 5, 2, 1, 1)
        self.check_INSTITUTE_UPDATE = QtWidgets.QCheckBox(Dialog)
        self.check_INSTITUTE_UPDATE.setObjectName("check_INSTITUTE_UPDATE")
        self.gridLayout.addWidget(self.check_INSTITUTE_UPDATE, 10, 2, 1, 1)
        self.check_INSTITUTE_QUERY = QtWidgets.QCheckBox(Dialog)
        self.check_INSTITUTE_QUERY.setObjectName("check_INSTITUTE_QUERY")
        self.gridLayout.addWidget(self.check_INSTITUTE_QUERY, 8, 2, 1, 1)
        self.check_HUMAN_QUERY = QtWidgets.QCheckBox(Dialog)
        self.check_HUMAN_QUERY.setObjectName("check_HUMAN_QUERY")
        self.gridLayout.addWidget(self.check_HUMAN_QUERY, 3, 2, 1, 1)
        self.button = QtWidgets.QPushButton(Dialog)
        self.button.setObjectName("button")
        self.gridLayout.addWidget(self.button, 23, 3, 1, 1)
        self.check_HUMAN_DELETE = QtWidgets.QCheckBox(Dialog)
        self.check_HUMAN_DELETE.setObjectName("check_HUMAN_DELETE")
        self.gridLayout.addWidget(self.check_HUMAN_DELETE, 7, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.check_POSITION_CONFIRM = QtWidgets.QCheckBox(Dialog)
        self.check_POSITION_CONFIRM.setObjectName("check_POSITION_CONFIRM")
        self.gridLayout.addWidget(self.check_POSITION_CONFIRM, 21, 2, 1, 1)
        self.check_POSITION_DELETE = QtWidgets.QCheckBox(Dialog)
        self.check_POSITION_DELETE.setObjectName("check_POSITION_DELETE")
        self.gridLayout.addWidget(self.check_POSITION_DELETE, 22, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(311, 31))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.check_POSITION_UPDATE = QtWidgets.QCheckBox(Dialog)
        self.check_POSITION_UPDATE.setObjectName("check_POSITION_UPDATE")
        self.gridLayout.addWidget(self.check_POSITION_UPDATE, 20, 2, 1, 1)
        self.check_SALARY_QUERY = QtWidgets.QCheckBox(Dialog)
        self.check_SALARY_QUERY.setObjectName("check_SALARY_QUERY")
        self.gridLayout.addWidget(self.check_SALARY_QUERY, 13, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.check_POSITION_CREATE = QtWidgets.QCheckBox(Dialog)
        self.check_POSITION_CREATE.setObjectName("check_POSITION_CREATE")
        self.gridLayout.addWidget(self.check_POSITION_CREATE, 19, 2, 1, 1)
        self.check_POSITION_QUERY = QtWidgets.QCheckBox(Dialog)
        self.check_POSITION_QUERY.setObjectName("check_POSITION_QUERY")
        self.gridLayout.addWidget(self.check_POSITION_QUERY, 18, 2, 1, 1)
        self.check_HUMAN_COMFIRM = QtWidgets.QCheckBox(Dialog)
        self.check_HUMAN_COMFIRM.setObjectName("check_HUMAN_COMFIRM")
        self.gridLayout.addWidget(self.check_HUMAN_COMFIRM, 6, 2, 1, 1)
        self.check_INSTITUTE_CREATE = QtWidgets.QCheckBox(Dialog)
        self.check_INSTITUTE_CREATE.setObjectName("check_INSTITUTE_CREATE")
        self.gridLayout.addWidget(self.check_INSTITUTE_CREATE, 9, 2, 1, 1)
        self.check_SALARY_CONFIRM = QtWidgets.QCheckBox(Dialog)
        self.check_SALARY_CONFIRM.setObjectName("check_SALARY_CONFIRM")
        self.gridLayout.addWidget(self.check_SALARY_CONFIRM, 16, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.check_SALARY_DELETE = QtWidgets.QCheckBox(Dialog)
        self.check_SALARY_DELETE.setObjectName("check_SALARY_DELETE")
        self.gridLayout.addWidget(self.check_SALARY_DELETE, 17, 2, 1, 1)
        self.check_SALARY_UPDATE = QtWidgets.QCheckBox(Dialog)
        self.check_SALARY_UPDATE.setObjectName("check_SALARY_UPDATE")
        self.gridLayout.addWidget(self.check_SALARY_UPDATE, 15, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.check_HUMAN_CREATE.setText(_translate("Dialog", "人事登记"))
        self.check_INSTITUTE_DELETE.setText(_translate("Dialog", "机构删除"))
        self.check_SALARY_CREATE.setText(_translate("Dialog", "薪酬登记"))
        self.check_INSTITUTE_CONFIRM.setText(_translate("Dialog", "机构复核"))
        self.check_HUMAN_UPDATE.setText(_translate("Dialog", "人事变更"))
        self.check_INSTITUTE_UPDATE.setText(_translate("Dialog", "机构变更"))
        self.check_INSTITUTE_QUERY.setText(_translate("Dialog", "机构查询"))
        self.check_HUMAN_QUERY.setText(_translate("Dialog", "人事查询"))
        self.button.setText(_translate("Dialog", "提交"))
        self.check_HUMAN_DELETE.setText(_translate("Dialog", "人事删除"))
        self.check_POSITION_CONFIRM.setText(_translate("Dialog", "职位复核"))
        self.check_POSITION_DELETE.setText(_translate("Dialog", "职位删除"))
        self.label.setText(_translate("Dialog", "权限角色名称："))
        self.check_POSITION_UPDATE.setText(_translate("Dialog", "职位变更"))
        self.check_SALARY_QUERY.setText(_translate("Dialog", "薪酬查询"))
        self.check_POSITION_CREATE.setText(_translate("Dialog", "职位登记"))
        self.check_POSITION_QUERY.setText(_translate("Dialog", "职位查询"))
        self.check_HUMAN_COMFIRM.setText(_translate("Dialog", "人事复核"))
        self.check_INSTITUTE_CREATE.setText(_translate("Dialog", "机构登记"))
        self.check_SALARY_CONFIRM.setText(_translate("Dialog", "薪酬复核"))
        self.check_SALARY_DELETE.setText(_translate("Dialog", "薪酬删除"))
        self.check_SALARY_UPDATE.setText(_translate("Dialog", "薪酬变更"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

